export let countryData=[
    { countryName: "afghanistan", citites: ["kabul", "gaaaf", "dan", "dafcc"] },
    { countryName: "land Island", citites: ["pabul", "apa", "bdab", "ccat"] },
    { countryName: "Albania", citites: ["falco", "daa", "sadbb", "facc"] },
    { countryName: "Algeria", citites: ["gdas", "aads", "dsa", "cddc"] },
    { countryName: "Samoa", citites: ["fabs", "asdsaa", "asdbb", "cac"] },
    { countryName: "AndorrA", citites: ["pakabul", "faaa", "fabb", "dascc"] },
    { countryName: "Angola", citites: ["faskabul", "ada", "abb", "cdac"] },
    { countryName: "Anguilla", citites: ["kdaabul", "adsaa", "fgbb", "cat"] },
    { countryName: "Antarctica", citites: ["deli", "mumdbai", "udsap"] },
    { countryName: "Antigua", citites: ["gat", "gert", "udsap"] },
    { countryName: "Argentina", citites: ["mehli", "numbai", "pup"] },
    { countryName: "Armenia", citites: ["lehli", "lumbai", "rup"] },
    { countryName: "Aruba", citites: ["sehli", "mumbai", "uep"] },
    { countryName: "Australia", citites: ["pehli"] },
    { countryName: "Austria", citites: [ "sumbai"] },
    { countryName: "Azerbaijan", citites: [ "dumbai"] },
     { countryName: "Bahamas", citites: [ "gumbai"] },
      { countryName: "Bangladesh", citites: [ "humbai"] },
      { countryName: "Czech", citites: [ "lumbai"] },
      { countryName: "Dominican", citites: [ "kumbai"] },
      { countryName: "Ecuador", citites: [ "oumbai"] },
      { countryName: "Egypt", citites: [ "lumbai"] },
      { countryName: "France", citites: [ "tumbai"] },
      { countryName: "Gambia", citites: [ "eumbai"] },
      { countryName: "Hungary", citites: [ "rumbai"] },
      { countryName: "Iceland", citites: [ "gumbai"] },
      { countryName: "India", citites: [ "lumbai", "up"] },
      { countryName: "Jordan", citites: [ "saumbai", "up"] },
      { countryName: "Kiribati", citites: [ "saumbai", "up"] },
      { countryName: "Latvia", citites: [ "msaumbai", "up"] },
      { countryName: "Malawi", citites: [ "mudmbai", "up"] },
      { countryName: "Nauru", citites: [ "mumbddai", "fup"] },
        { countryName: "Oman", citites: [ "mumbadai", "fup"] },  { countryName: "Malawi", citites: [ "kokla", "saup"] },
        { countryName: "Philippines", citites: [ "emumbai", "sup"] },
        { countryName: "Qatar", citites: [ "eamumbai", "rup"] },
        { countryName: "Reunion", citites: [ "samumbai", "gup"] },
        { countryName: "Saint", citites: [ "mudsmbai", "fup"] },
        { countryName: "Tunisia", citites: [ "mudsmbai", "fup"] },
        { countryName: "Uzbekistan", citites: [ "sdasmumbai", "dup"] },
        { countryName: "Venezuela", citites: [ "pomumbai", "vup"] },
        { countryName: "Wallis", citites: [ "medamumbai", "cup"] },
        { countryName: "Yemen", citites: [ "dsmumbai", "bup"] },
        { countryName: "Zimbabwe", citites: [ "kamumbai", "aup"] },

  ];